export enum ROLES {
  CLIENT = "CLIENT",
  ADMIN = "ADMIN"
}
export enum TYPE {
  SELECT_ENGLISH_WORDS = "SELECT_ENGLISH_WORDS",
  LISTEN_AND_SELECT_WORD = "LISTEN_AND_SELECT_WORD",
  DESCRIBE_THE_IMAGE = "DESCRIBE_THE_IMAGE",
  RECORD_SAYING_STATEMENT = "RECORD_SAYING_STATEMENT",
  RESPOND_N_WORDS = "RESPOND_N_WORDS"
}
