export enum ROLES {
  CLIENT = "CLIENT",
  ADMIN = "ADMIN"
}

export const BASE_URL = "http://bilingual.peaksoftprojects.com/graphql";

export enum QUESTION_TYPES {
  SELECT_ENGLISH_WORDS = "SELECT_ENGLISH_WORDS",
  LISTEN_AND_SELECT_WORD = "LISTEN_AND_SELECT_WORD",
  DESCRIBE_THE_IMAGE = "DESCRIBE_THE_IMAGE",
  TYPE_WHAT_YOU_HEAR = "TYPE_WHAT_YOU_HEAR",
  RECORD_SAYING_STATEMENT = "RECORD_SAYING_STATEMENT",
  RESPOND_N_WORDS = "RESPOND_N_WORDS"
}
