export enum ROLES {
  CLIENT = "CLIENT",
  ADMIN = "ADMIN"
}
export enum QUESTION_TYPES {
  SELECT_ENGLISH_WORDS = "SELECT_ENGLISH_WORDS",
  LISTEN_AND_SELECT_WORD = "LISTEN_AND_SELECT_WORD",
  DESCRIBE_THE_IMAGE = "DESCRIBE_THE_IMAGE",
  TYPE_WHAT_YOU_HEAR = "TYPE_WHAT_YOU_HEAR",
  RECORD_SAYING_STATEMENT = "RECORD_SAYING_STATEMENT",
  RESPOND_N_WORDS = "RESPOND_N_WORDS",
  HIGHLIGHT_THE_ANSWER = "HIGHLIGHT_THE_ANSWER",
  SELECT_THE_MAIN_IDEA = "SELECT_THE_MAIN_IDEA",
  SELECT_BEST_TITLE = "SELECT_BEST_TITLE"
}
