version: 2.1

parameters:
  docker-container:
    type: string
    default: "billingual-web"
  branch:
    type: string
    default: "development"

jobs:
  install-docker-if-not-exists:
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Install SSH And Configure
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ./privateKey.pem
            chmod 400 privateKey.pem
      - run:
          name: Install Docker If Not Exists
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./privateKey.pem ubuntu@$HOST '
            if [[ ! $(sudo docker -v) ]]; then
               sudo snap install docker
            fi'
  build-image:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t << pipeline.parameters.docker-container >>:latest .
      - run:
          name: Compress Docker Image
          command: |
            docker save << pipeline.parameters.docker-container >>:latest | gzip > << pipeline.parameters.docker-container >>.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - << pipeline.parameters.docker-container >>.tar.gz
  transfer-and-run:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install SSH And Configure
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ./privateKey.pem
            chmod 400 privateKey.pem
      - run:
          name: Stop Remote Docker Container If Exists with name << pipeline.parameters.docker-container >> even not working
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./privateKey.pem ubuntu@$HOST '
                if [[ $(sudo docker ps -a -q -f name=<< pipeline.parameters.docker-container >>) ]]; then
                    sudo docker rm -f << pipeline.parameters.docker-container >>
                    sudo docker rmi << pipeline.parameters.docker-container >>:latest
                fi
            '
      - run:
          name: Transfer File
          command: |
            scp -o "StrictHostKeyChecking=no" -i ./privateKey.pem ./<< pipeline.parameters.docker-container >>.tar.gz ubuntu@$HOST:~/
      - run:
          name: Decompress Docker Image | Run Compose
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./privateKey.pem ubuntu@$HOST '
            sudo gunzip -c ./<< pipeline.parameters.docker-container >>.tar.gz | sudo docker load
            sudo rm ./<< pipeline.parameters.docker-container >>.tar.gz
            sudo docker run -d --name << pipeline.parameters.docker-container >> -p 80:80 --restart unless-stopped << pipeline.parameters.docker-container >>:latest
            '

workflows:
  deploy:
    jobs:
      - install-docker-if-not-exists:
          filters:
            branches:
              only:
                - << pipeline.parameters.branch >>
      - build-image:
          requires:
            - install-docker-if-not-exists
          filters:
            branches:
              only:
                - << pipeline.parameters.branch >>
      - transfer-and-run:
          requires:
            - build-image
          filters:
            branches:
              only:
                - << pipeline.parameters.branch >>
